Added Contributing.md
hackclub/hackathons pull request #38
Opened 2021-03-05 04:52 UTC by nimit2801

- Added the contributing.md for [Hackathons](https://github.com/hackclub/hackathons)
- With some cool gifs and informative images
- Solving #37 
- Please review thank you.

2021-03-05 08:47 UTC, sampoder requested changes
Thanks for contributing :)

Unfortunately, I don't think this is up to standard. A few pointers:

- Headings should only be used for headings not body text
- The grammar needs significant improving 
- The "vibe" of the text feels off, it feels unprofessional but not in a good way

Hope you can understand

2021-03-08 21:57 UTC, nimit2801 commented
@sampoder I've made the changes requested.
Thank for the review.

> 
> 
> Thanks for contributing :)
> 
> Unfortunately, I don't think this is up to standard. A few pointers:
> 
>     * Headings should only be used for headings not body text
> 
>     * The grammar needs significant improving
> 
>     * The "vibe" of the text feels off, it feels unprofessional but not in a good way
> 
> 
> Hope you can understand

2021-03-14 13:15 UTC, sampoder requested changes
It's better, but there are still a lot of grammar errors

2021-03-15 01:35 UTC, nimit2801 commented
> 
> 
> It's better, but there are still a lot of grammar errors

Can you tell me which lines I should, improve or some suggestions.
Thank You.

2021-03-15 02:21 UTC, sampoder commented on CONTRIBUTING.md
> +#### This document contains a set of guidelines that any contributions to any Hack Club repository must follow.
G

2021-03-15 02:22 UTC, sampoder commented on CONTRIBUTING.md
> +Fork the original repo [hackathons](https://github.com/hackclub/hackathons) !
G

2021-03-15 02:22 UTC, sampoder commented on CONTRIBUTING.md
> +Something in your URL would look like this:
G

2021-03-15 02:22 UTC, sampoder commented on CONTRIBUTING.md
> +eg: In my case, I was adding the CONTRIBUTING.md
G

2021-03-15 02:23 UTC, sampoder commented
View above comments. Each has a grammar / phrasing issue.

2021-03-15 02:23 UTC, sampoder commented
Also this document still doesn't feel right. IMO it should be made more professional

2021-03-15 02:31 UTC, nimit2801 commented
I'll reformat it, and update my PR!
@sampoder thanks for the review.

2021-11-07 02:18 UTC, closed without merging